version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_PASSWORD=mysqlpass
      - MYSQL_USER=mysqluser
      - MYSQL_DATABASE=reddit-stories
