version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 18, 16, 14.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16-bullseye
    env_file: devcontainer.env
    volumes:
      - ..:/workspace:cached
      - /workspace/node_modules
      - /workspace/.next
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    network_mode: host
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_PASSWORD=mysqlpass
      - MYSQL_USER=mysqluser
      - MYSQL_DATABASE=reddit-stories
