import * as React from 'react';
import type { NextPage } from 'next';
import useSWR from 'swr';
import Head from 'next/head';
import Image from 'next/image';
import CommentsContainer from '../components/CommentsContainer';
import Post from '../components/Post';
import { CommentDetails, IPost } from '../interfaces/reddit';
import styles from '../styles/Home.module.css';
import { fetchFromUrl } from '../helpers/fetchData';
import { getAllPrompts } from '../helpers/cleanData';

const Home: NextPage = () => {

  const { data } = useSWR("/r/WritingPrompts/hot", fetchFromUrl)
  const [postsData, setPostsData] = React.useState<IPost[]>();
  const [selectedPost, setSelectedPost] = React.useState<IPost>();

  React.useEffect(() => {
    if (data) {
      setPostsData(getAllPrompts(data));
    }
  }, [data])

  const selectPost = (id: string) => {
    if (postsData) {
      let postWithId = postsData.find((val) => val.id === id);
      if (postWithId) {
        setSelectedPost(postWithId);
      }
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.mainContainer}>
        <div className={styles.postsContainer}>
          {postsData ? postsData?.map((prompt) => {
            return <Post key={prompt.id} title={prompt.title} author={prompt.author} id={prompt.id} permalink={prompt.permalink} score={prompt.score} stories={prompt.stories} created={prompt.created} selectPost={selectPost} />
          }) : <p>Loading...</p>}
        </div>

      </div>


    </div>
  )
}

export default Home
